import argparse

DATA_FOLDER = "./DATA_ROOT"

parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument("--experiment_name", type=str, default="experiment_name")
parser.add_argument("--dataset", type=str, default="mit-states")
parser.add_argument("--clip_model", type=str, default="ViT-L/14")
parser.add_argument("--context_length", default=13, type=int)
parser.add_argument("--seed", default=0, type=int)
parser.add_argument("--phase", default="train", type=str)
parser.add_argument("--device", default="cuda:5", type=str)
parser.add_argument("--load_model", default="None", type=str)
parser.add_argument("--use_soft_embeddings", type=str, default="None")
parser.add_argument("--train_soft_embeddings", type=str, default="True", )
parser.add_argument("--train_token_embeddings", type=str, default="false", )
parser.add_argument("--embedding_type", help="complete,separate", default="complete", type=str)
parser.add_argument("--multi_prompt_type", default="True", type=str)
parser.add_argument("--lr", type=float, default=5e-5)
parser.add_argument("--weight_decay", type=float, default=5e-5)
parser.add_argument("--epochs", default=40, type=int)
parser.add_argument("--train_batch_size", default=256, type=int)
parser.add_argument("--save_path", type=str, default="./logs/mit-states")
parser.add_argument("--save_every_n", default=1, type=int)
parser.add_argument("--save_model", default="True", type=str)
parser.add_argument("--start_epoch", default=1, type=int)
parser.add_argument("--eval_epoch", default=-1, type=int)
parser.add_argument("--dropout", type=float, default=0.3)
parser.add_argument("--graph_init", default="None", type=str)
parser.add_argument("--l_adapter_layers", default=3, type=int)
parser.add_argument("--v_adapter_layers", default=3, type=int)
parser.add_argument("--hidden_layers", default="d4096,d", type=str)
parser.add_argument("--split_cal_size", default=1000, type=int)
parser.add_argument("--eval_batch_size", default=64, type=int)
parser.add_argument("--bias", type=float, default=1e3)
parser.add_argument("--topk", type=int, default=1)
parser.add_argument("--eval_load_model", default="None", type=str)
parser.add_argument("--eval_use_soft_embeddings", type=str, default="None")
parser.add_argument("--threshold", type=float)
parser.add_argument("--threshold_trials", type=int, default=50)
parser.add_argument("--open_world", action="store_true")
parser.add_argument("--accu", type=int, default=1)
parser.add_argument("--has_l_adapter", default="True", type=str)
parser.add_argument("--has_v_adapter", default="True", type=str)
parser.add_argument("--l_adapter_context", default="True", type=str)
parser.add_argument("--v_adapter_context", default="True", type=str)
parser.add_argument("--l_adapter_location", default="in", type=str)
parser.add_argument("--v_adapter_location", default="out", type=str)


